### ISSUE TITLE
Simplify kinesis starter configuration for internal communication

### ISSUE THREAD

**Issue by andrejivanov** [bringmeister/aws-kinesis-spring-boot-starter#15]
Current kinesis starter needs configuration to assume role that includes privileges to write or read to/from kinesis stream. IMHO this is only necessary for communication to outside own AWS account.
For internal communication I would like to save effort and provision additional role that reference account itself and write simple configuration:

```
consumer: 
 - stream-name: foo-event-stream
```

instead of
```
consumer: 
 - stream-name: foo-event-stream
        aws-account-id: "490528281704"
        iam-role-to-assume: TeamConnectKinesisConsumer
```
